name: Go Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  releases-matrix:
    name: Release Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          binary_name=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            binary_name="multicast-tool.exe"
          else
            binary_name="multicast-tool"
          fi
          go build -o $binary_name main.go
          
      - name: Archive Release
        run: |
          if [ "${{ matrix.goos }}" = "windows" ]; then
            zip "multicast-tool-${{ matrix.goos }}-${{ matrix.goarch }}.zip" multicast-tool.exe
          else
            tar czvf "multicast-tool-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz" multicast-tool
          fi
          
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            multicast-tool-${{ matrix.goos }}-${{ matrix.goarch }}.zip
            multicast-tool-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}